object FCorp: TFCorp
  Left = 329
  Top = 104
  ActiveControl = Dbg
  AutoSize = True
  BiDiMode = bdRightToLeft
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = '„⁄—›Ì ‘—ﬂ '
  ClientHeight = 426
  ClientWidth = 536
  Color = clBtnFace
  ParentFont = True
  KeyPreview = True
  OldCreateOrder = False
  ParentBiDiMode = False
  Position = poDesktopCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Bevel1: TBevel
    Left = 2
    Top = 0
    Width = 534
    Height = 405
  end
  object Sp: TSpeedButton
    Left = 371
    Top = 377
    Width = 23
    Height = 22
    Caption = '...'
    Flat = True
    OnClick = SpClick
  end
  object Label1: TLabel
    Left = 408
    Top = 6
    Width = 113
    Height = 17
    AutoSize = False
    Caption = '‰«„ ò«„ÅÌÊ — ”—Ê—'
  end
  object Edit1: TEdit
    Left = 431
    Top = 378
    Width = 95
    Height = 21
    Hint = '«›“«Ì‘ ”—⁄  „Õ«”»« '
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    Text = '0'
  end
  object UpDown1: TUpDown
    Left = 416
    Top = 378
    Width = 15
    Height = 21
    AlignButton = udLeft
    Associate = Edit1
    Min = 0
    Max = 20480
    Increment = 512
    Position = 0
    TabOrder = 1
    Thousands = False
    Wrap = False
  end
  object StatusBar1: TStatusBar
    Left = 0
    Top = 407
    Width = 535
    Height = 19
    Align = alNone
    Panels = <
      item
        Text = '  Ctrl+Del =Õ–› —œÌ›             Ins=«›“Êœ‰ —œÌ› ÃœÌœ'
        Width = 50
      end>
    SimplePanel = False
  end
  object Dbg: TDBGrid
    Left = 2
    Top = 28
    Width = 530
    Height = 346
    DataSource = Ds
    TabOrder = 3
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'MS Sans Serif'
    TitleFont.Style = []
    OnEditButtonClick = DbgEditButtonClick
    OnKeyDown = DbgKeyDown
    OnKeyPress = DbgKeyPress
    Columns = <
      item
        ButtonStyle = cbsEllipsis
        Expanded = False
        FieldName = 'FName'
        Width = 114
        Visible = True
      end
      item
        ButtonStyle = cbsEllipsis
        Expanded = False
        FieldName = 'DBName'
        Title.Caption = '‰«„ »«‰ò «ÿ·«⁄« Ì'
        Width = 109
        Visible = True
      end
      item
        Alignment = taRightJustify
        Expanded = False
        FieldName = 'Server'
        Title.Caption = '‰«„ ”—Ê—'
        Width = 119
        Visible = True
      end
      item
        Expanded = False
        FieldName = 'User'
        Title.Caption = 'ò«—»—'
        Width = 99
        Visible = True
      end
      item
        Expanded = False
        FieldName = 'Pass'
        Title.Caption = '—„“⁄»Ê—'
        Visible = True
      end>
  end
  object FNet: TEdit
    Left = 5
    Top = 377
    Width = 361
    Height = 21
    TabStop = False
    BiDiMode = bdLeftToRight
    ParentBiDiMode = False
    ReadOnly = True
    TabOrder = 4
  end
  object cnCName: TComboBox
    Left = 262
    Top = 4
    Width = 145
    Height = 21
    TabStop = False
    ItemHeight = 13
    TabOrder = 5
  end
  object T1: TTable
    Tag = 1
    BeforeInsert = T1BeforeInsert
    BeforeScroll = T1BeforeScroll
    AutoRefresh = True
    DatabaseName = 'D:\Applications\Forooshes\Parsian Foroosh V5 SQL'
    TableName = 'ParAcc'
    TableType = ttParadox
    Left = 357
    Top = 74
    object T1FName: TStringField
      DisplayLabel = '‰«„ ‘—ò  Ì« ”«· „«·Ì'
      DisplayWidth = 22
      FieldName = 'FName'
      Required = True
      Size = 45
    end
    object T1DbName: TStringField
      Alignment = taRightJustify
      DisplayLabel = '„”Ì— ‰êÂœ«—Ì «ÿ·«⁄« '
      DisplayWidth = 51
      FieldName = 'DBName'
      Required = True
      Size = 100
    end
    object T1Server: TStringField
      DisplayLabel = '”—Ê—'
      DisplayWidth = 30
      FieldName = 'Server'
      Size = 45
    end
    object T1User: TStringField
      FieldName = 'User'
      Size = 45
    end
    object T1Pass: TStringField
      FieldName = 'Pass'
      Size = 16
    end
  end
  object Ds: TDataSource
    DataSet = T1
    Left = 384
    Top = 72
  end
  object Q: TQuery
    SQL.Strings = (
      ''
      'CREATE TABLE [dbo].[AcBillList] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bedeh] [money] NULL ,'
      #9'[Bestan] [money] NULL ,'
      #9'[Ackod] [decimal](18, 0) NULL ,'
      #9'[Acgir] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Accnam] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[AccountKod] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Kkol] [int] NULL ,'
      #9'[Kmo] [int] NULL ,'
      #9'[Kgro] [int] NULL ,'
      #9'[Ktaf] [int] NULL ,'
      #9'[Kdas] [int] NULL ,'
      #9'[Usekod] [smallint] NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Mah] [int] NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Adr] [varchar] (140) NULL ,'
      #9'[Pcred] [money] NULL ,'
      #9'[Ename] [varchar] (45) NULL ,'
      #9'[Kgp] [int] NULL ,'
      #9'[State] [varchar] (45) NULL ,'
      #9'[City] [varchar] (45) NULL ,'
      #9'[Regon] [varchar] (20) NULL,'
      '     [Barzi] [bit] NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[AccountPay] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Bednam] [varchar] (45) NULL ,'
      #9'[Besnam] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cwage] [money] NULL,'
      '     [Lperm] [bit] NOT NULL ,'
      '     [Ckod2] [int] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[AcountBill] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bed] [money] NULL ,'
      #9'[Bes] [money] NULL ,'
      #9'[Ackod] [decimal](18, 0) NULL ,'
      #9'[Accnam] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Facno] [varchar] (30) NULL ,'
      #9'[Btip] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Tip] [smallint] NULL ,'
      #9'[Cbed] [money] NULL ,'
      #9'[Cbes] [money] NULL ,'
      #9'[Rate] [float] NULL ,'
      #9'[Ctip] [varchar] (15) NULL,'
      '     [Dchek] [bit] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Aghs] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Gprice] [money] NULL ,'
      #9'[RNo] [int] NULL ,'
      #9'[Payed] [bit] NOT NULL ,'
      #9'[RDat] [int] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[AnbDat] ('
      #9'[Kod] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Nam] [varchar] (45) NOT NULL ,'
      #9'[Adr] [varchar] (145) NULL ,'
      #9'[Admin] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Autobill] ('
      #9'[Var] [varchar] (10) NOT NULL ,'
      #9'[Caption] [varchar] (45) NOT NULL ,'
      #9'[BesKod] [decimal](18, 0) NULL ,'
      #9'[BehKod] [decimal](18, 0) NULL ,'
      #9'[Stat] [bit] NOT NULL'
      ') ON [PRIMARY]'
      ''
      ''
      'CREATE TABLE [dbo].[Banks] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Bnam] [varchar] (45) NOT NULL ,'
      #9'[Bkod] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[BHav] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Jari] [varchar] (20) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Facno] [int] NULL ,'
      #9'[Accnam] [varchar] (45) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cwage] [money] NULL,'
      '     [Lperm] [bit] NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Bill] ('
      #9'[id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bedsum] [money] NULL ,'
      #9'[Bessum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Atf] [int] NULL ,'
      #9'[Tip] [smallint] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[BillD] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bedsum] [money] NULL ,'
      #9'[Bessum] [money] NULL ,'
      #9'[Des] [varchar] (200) COLLATE Arabic_CI_AS NULL ,'
      #9'[Lperm] [bit] NOT NULL ,'
      #9'[Atf] [int] NULL ,'
      #9'[Tip] [smallint] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[BinvoGood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [float] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Bfee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Pay] [money] NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Garan] [varchar] (45) NULL ,'
      #9'[Prop] [varchar] (200) NULL'
      ') ON [PRIMARY]'
      ''
      ''
      'CREATE TABLE [dbo].[BTip] ('
      #9'[Id] [smallint] NOT NULL ,'
      #9'[Des] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Bvoice] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Visit] [int] NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Prule] [varchar] (30) NULL ,'
      #9'[Ppay] [money] NULL ,'
      #9'[Prem] [money] NULL ,'
      #9'[Plc] [money] NULL ,'
      #9'[PGom] [money] NULL ,'
      #9'[Ptar] [money] NULL ,'
      #9'[Pdemo] [money] NULL ,'
      #9'[Pcar] [money] NULL ,'
      #9'[Poth] [money] NULL ,'
      #9'[Pcost] [money] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Cardex] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anb] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[IIn] [float] NULL ,'
      #9'[Out] [float] NULL ,'
      #9'[Rem] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Des] [varchar] (20) NULL ,'
      #9'[Facnam] [varchar] (45) NULL ,'
      #9'[Fee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Prem] [money] NULL ,'
      #9'[Diag] [float] NULL ,'
      #9'[Pdiag] [money] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Cashiers] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Name] [varchar] (45) NULL ,'
      #9'[Owner] [varchar] (45) NOT NULL ,'
      #9'[Ctip] [varchar] (20) NULL ,'
      #9'[Ackod] [decimal](18, 0) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Cent] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Kod] [int] NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Ename] [varchar] (45) NULL ,'
      #9'[Grop] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Adr] [varchar] (140) NULL ,'
      #9'[Pcred] [money] NULL ,'
      #9'[Tcred] [int] NULL ,'
      #9'[State] [varchar] (45) NULL ,'
      #9'[City] [varchar] (45) NULL ,'
      #9'[Regon] [varchar] (20) NULL ,'
      #9'[Shmark] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Cexchange] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Acnam] [varchar] (50) NOT NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Amount] [money] NOT NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[IAmount] [money] NOT NULL ,'
      #9'[ICtip] [varchar] (15) NOT NULL ,'
      #9'[ExchAc] [decimal](18, 0) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Des] [varchar] (200) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Colors] ('
      #9'[Color] [varchar] (45) NOT NULL ,'
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Costc] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Des] [varchar] (200) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[CPerm] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ackod] [float] NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      '     [Grop] [varchar] (45)  NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[CRate] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Cname] [varchar] (15) NULL ,'
      #9'[Fee] [money] NULL ,'
      #9'[Dat] [int] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[CTip] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Name] [varchar] (15) NULL ,'
      #9'[Sign] [varchar] (5) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Depot] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Gene] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [float] NULL ,'
      #9'[Quant] [float] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DHav] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL,'
      '     [Des] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DHavG] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DiRej] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL ,'
      '     [Des] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DiRejG] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DoRej] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL ,'
      '     [Des] [varchar] (45) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DoRejG] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Dout] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) COLLATE Arabic_CI_AS NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL ,'
      #9'[Des] [varchar] (200) COLLATE Arabic_CI_AS NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DoutG] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DRes] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Refno] [int] NULL,'
      '     [Des] [varchar] (200) COLLATE Arabic_CI_AS NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[DResG] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Anbnam] [varchar] (45) NULL ,'
      #9'[Anbkod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Expen] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Accnam] [varchar] (50) COLLATE Arabic_CI_AS NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Cost] [varchar] (50) COLLATE Arabic_CI_AS NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) COLLATE Arabic_CI_AS NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Lperm] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[ExpenD] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[ItNo] [int] NULL ,'
      #9'[Acnam] [varchar] (50) COLLATE Arabic_CI_AS NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Amount] [money] NULL ,'
      #9'[Ctip] [smallint] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Des] [varchar] (160) COLLATE Arabic_CI_AS NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[No] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[FTip] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Des] [varchar] (45) NULL ,'
      '     [Beskod] [decimal](18, 0) NULL ,'
      #9'[Bedkod] [decimal](18, 0) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[GarDesh] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bedeh] [money] NULL ,'
      #9'[Bestan] [money] NULL ,'
      #9'[BedRem] [money] NULL ,'
      #9'[BesRem] [money] NULL ,'
      #9'[Baghi] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Diag] [money] NULL ,'
      '     [Ctip] [varchar] (40) NULL,'
      '     [Bid] [int] NULL ,'
      #9'[Dchek] [bit] NOT NULL'
      ''
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[GCardex] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[IOkod] [smallint] NULL ,'
      #9'[AnbNam] [varchar] (45) NULL ,'
      #9'[AnbKod] [int] NULL ,'
      #9'[FacNo] [int] NULL ,'
      #9'[FacNam] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (20) NULL ,'
      #9'[Fee] [money] NULL ,'
      #9'[Perc] [float] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[GChart] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Des] [varchar] (45) NULL ,'
      #9'[Kol] [smallint] NULL ,'
      #9'[Mo] [smallint] NULL ,'
      #9'[Taf] [smallint] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Gform] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100)  NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Mkod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[GGoz] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Good] [varchar] (100) NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Fee] [money] NULL ,'
      #9'[Total] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Goods] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Kol] [smallint] NULL ,'
      #9'[Mo] [smallint] NULL ,'
      #9'[Taf] [smallint] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Pkh] [money] NULL ,'
      #9'[Pfro] [money] NULL ,'
      #9'[Gene] [int] NULL ,'
      #9'[Rquant] [float] NULL ,'
      #9'[Bquant] [float] NULL ,'
      #9'[Fdp] [bit] NOT NULL ,'
      #9'[Prop1] [varchar] (100) NULL ,'
      #9'[Prop2] [varchar] (100) NULL ,'
      #9'[Prop3] [varchar] (100) NULL ,'
      #9'[Prop4] [varchar] (100) NULL ,'
      #9'[ISBN] [varchar] (50) NULL ,'
      #9'[Prule] [varchar] (10) NULL,'
      '     [Flock] [bit] NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Invogood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[AnbNam] [varchar] (45) NULL ,'
      #9'[AnbKod] [float] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Garan] [varchar] (45) NULL ,'
      #9'[Prop] [varchar] (200) NULL ,'
      #9'[OPfee] [money] NULL ,'
      #9'[OPSum] [money] NULL ,'
      '     [Qout] [float] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Invoice] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Adr] [varchar] (200) NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Ppay] [money] NULL ,'
      #9'[Prem] [money] NULL ,'
      #9'[Pcheq] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Visit] [int] NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Prule] [varchar] (30) NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[RefNo] [int] NULL ,'
      '     [Ptax] [money] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Jari] ('
      #9'[Idd] [int] IDENTITY (1, 1) NOT NULL ,'
      '     [Id] [int] NOT NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Bestan] [money] NULL ,'
      #9'[Bedeh] [money] NULL ,'
      #9'[Rema] [money] NULL ,'
      #9'[Des] [varchar] (140) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[JariN] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Bnam] [varchar] (45) NULL ,'
      #9'[Bkod] [varchar] (20) NULL ,'
      #9'[DJari] [varchar] (45) NULL ,'
      #9'[AccKod] [decimal](18, 0) NULL ,'
      #9'[CheqKod] [decimal](18, 0) NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Mali] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[BDes] [varchar] (150) NULL ,'
      #9'[Bed] [money] NULL ,'
      #9'[SDes] [varchar] (150) NULL ,'
      #9'[Bes] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Move] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[LPerm] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[MoveGood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[OAnbNam] [varchar] (45) NULL ,'
      #9'[OAnbKod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[IAnbNam] [varchar] (45) NULL ,'
      #9'[IAnbKod] [int] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Prop] [varchar] (50) NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[NCar] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Jari] [varchar] (20) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[NFish] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Jari] [varchar] (20) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Accnam] [varchar] (45) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cwage] [money] NULL,'
      '     [Lperm] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Pcheq] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Paydat] [int] NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Bkod] [varchar] (20) NULL ,'
      #9'[Jari] [varchar] (20) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[Paykod] [bit] NOT NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Pkod] [decimal](18, 0) NULL ,'
      #9'[PBNo] [int] NULL ,'
      #9'[PaNo] [int] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[PInvogood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[AnbNam] [varchar] (45) NULL ,'
      #9'[AnbKod] [int] NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Garan] [varchar] (45) NULL ,'
      #9'[Prop] [varchar] (200) NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[PInvoice] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Adr] [varchar] (200) NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[Ppay] [money] NULL ,'
      #9'[Prem] [money] NULL ,'
      #9'[Pcheq] [money] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[DeliKod] [bit] NOT NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Visit] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[PMon] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Accnam] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cakod] [decimal](18, 0) NULL ,'
      #9'[Cwage] [money] NULL,'
      '     [Lperm] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rcheq] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[RecDat] [int] NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Bkod] [varchar] (20) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Dpay] [varchar] (65) NULL ,'
      #9'[Reckod] [bit] NOT NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Pacckod] [decimal](18, 0) NULL ,'
      #9'[Pacnam] [varchar] (45) NULL ,'
      #9'[Keler] [bit] NOT NULL ,'
      #9'[Jari] [varchar] (20) NULL ,'
      #9'[Reject] [bit] NOT NULL ,'
      #9'[Shar] [bit] NOT NULL ,'
      #9'[RBno] [int] NULL ,'
      #9'[PBno] [int] NULL ,'
      #9'[Pdat] [int] NULL ,'
      #9'[VBNo] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[PCost] [varchar] (45) NULL ,'
      #9'[PCkod] [int] NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RejBinvogood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[AnbNam] [varchar] (45) NULL ,'
      #9'[AnbKod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Bkod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Garan] [varchar] (45) NULL ,'
      #9'[Prop] [varchar] (200) NULL ,'
      #9'[OPfee] [money] NULL ,'
      #9'[OPSum] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RejBvoice] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[FacNo] [int] NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Visit] [int] NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[RefNo] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RejInvo] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Tel] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Adr] [varchar] (200) NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Pkol] [money] NULL ,'
      #9'[Pdis] [money] NULL ,'
      #9'[Pnet] [money] NULL ,'
      #9'[FacNo] [int] NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Visit] [int] NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[RefNo] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RejInvogood] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Kod] [int] NULL ,'
      #9'[Nam] [varchar] (100) NULL ,'
      #9'[Color] [varchar] (45) NULL ,'
      #9'[AnbNam] [varchar] (45) NULL ,'
      #9'[AnbKod] [int] NULL ,'
      #9'[Quant] [float] NULL ,'
      #9'[Unit] [varchar] (20) NULL ,'
      #9'[Pfee] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Ptotal] [money] NULL ,'
      #9'[Delikod] [bit] NOT NULL ,'
      #9'[Reject] [float] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Serial] [varchar] (20) NULL ,'
      #9'[Garan] [varchar] (45) NULL ,'
      #9'[Prop] [varchar] (200) NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Remit] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NOT NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[Acnam] [varchar] (50) NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[lperm] [bit] NOT NULL ,'
      #9'[Psum] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Remitin] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[ItNo] [int] NULL ,'
      #9'[Acnam] [varchar] (50) NOT NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Amount] [money] NULL ,'
      #9'[Ctip] [smallint] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Cwage] [money] NULL ,'
      #9'[Remfee] [varchar] (30) NULL ,'
      #9'[Code] [varchar] (35) NULL ,'
      #9'[Person] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (25) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[AccountDes] [varchar] (50) NULL ,'
      #9'[Des] [varchar] (130) NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[No] [int] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RemitOut] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[ItNo] [int] NULL ,'
      #9'[Acnam] [varchar] (50) NOT NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Amount] [money] NULL ,'
      #9'[Ctip] [smallint] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Cwage] [money] NULL ,'
      #9'[Remfee] [varchar] (30) NULL ,'
      #9'[Code] [varchar] (35) NULL ,'
      #9'[Person] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (25) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[AccountDes] [varchar] (50) NULL ,'
      #9'[Des] [varchar] (130) NULL ,'
      #9'[Dat] [int] NOT NULL ,'
      #9'[No] [int] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RKel] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[AccKod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rkeli] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Reject] [bit] NOT NULL ,'
      #9'[Jari] [varchar] (20) NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RMon] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Price] [money] NULL ,'
      #9'[Accnam] [varchar] (45) NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[BnO] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cakod] [decimal](18, 0) NULL ,'
      #9'[Cwage] [money] NULL ,'
      #9'[Lperm] [bit] NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RPay] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rpayi] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[No] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RRej] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[AccKod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rreji] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[Ackod] [float] NULL ,'
      #9'[No] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RRes] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Acckod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Inv] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL ,'
      #9'[Ctip] [varchar] (15) NULL ,'
      #9'[Cprice] [money] NULL ,'
      #9'[Rate] [money] NULL ,'
      #9'[Cwage] [money] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RSaf] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Adr] [varchar] (100) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[Statue] [varchar] (20) NULL ,'
      #9'[FNo] [int] NULL ,'
      #9'[Sprice] [money] NULL ,'
      #9'[Qt] [smallint] NULL ,'
      #9'[Pprice] [money] NULL ,'
      #9'[Daf] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RUKel] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[AccKod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[RUkeli] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Reject] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rvos] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[AccKod] [decimal](18, 0) NULL ,'
      #9'[Acnam] [varchar] (45) NULL ,'
      #9'[Psum] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL ,'
      #9'[Billed] [bit] NOT NULL ,'
      #9'[Bno] [int] NULL ,'
      #9'[Cost] [varchar] (45) NULL ,'
      #9'[Ckod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Rvosi] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Radif] [int] NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Bno] [varchar] (20) NULL ,'
      #9'[Bank] [varchar] (45) NULL ,'
      #9'[Pbill] [money] NULL ,'
      #9'[No] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Tolids] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[No] [int] NULL ,'
      #9'[Dat] [int] NULL ,'
      #9'[Eco] [varchar] (20) NULL ,'
      #9'[Inp] [money] NULL ,'
      #9'[Outp] [money] NULL ,'
      #9'[Des] [varchar] (200) NULL ,'
      #9'[LPerm] [bit] NOT NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Users] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[UserN] [varchar] (45) NULL ,'
      #9'[Password] [varchar] (8) NULL ,'
      #9'[Master] [bit] NOT NULL ,'
      #9'[Mali] [varchar] (255) NULL ,'
      #9'[Lang] [varchar] (4) NULL,'
      #9'[Centfilt] [varchar] (120)  NULL ,'
      #9'[Cashfilt] [varchar] (120)  NULL ,'
      '     [Idd] [int] NULL'
      ''
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[UserAc] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Userid] [int] NULL ,'
      #9'[Usern] [varchar] (50) NOT NULL ,'
      #9'[Acname] [varchar] (50) NOT NULL ,'
      #9'[Acckod] [decimal](18, 0) NOT NULL'
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[UserAct] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Uname] [varchar] (45) COLLATE Arabic_CI_AS NULL ,'
      #9'[Dat] [datetime] NULL ,'
      #9'[Doc] [varchar] (50) COLLATE Arabic_CI_AS NULL ,'
      #9'[Ddat] [int] NULL ,'
      #9'[Dno] [int] NULL ,'
      #9'[Dvalue] [float] NULL ,'
      #9'[Act] [varchar] (50) COLLATE Arabic_CI_AS NULL ,'
      #9'[Htime] [datetime] NULL ,'
      #9'[FDat] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[VAct] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Des] [varchar] (50)  NULL ,'
      #9'[QtRate] [money] NULL ,'
      #9'[Perc] [float] NULL ,'
      #9'[Kol] [smallint] NULL ,'
      #9'[Mo] [smallint] NULL ,'
      #9'[Taf] [smallint] NULL ,'
      #9'[Vkod] [int] NULL '
      ') ON [PRIMARY]'
      ''
      'CREATE TABLE [dbo].[Visitors] ('
      #9'[Id] [int] IDENTITY (1, 1) NOT NULL ,'
      #9'[Code] [int] NULL ,'
      #9'[Nam] [varchar] (45) NULL ,'
      #9'[Tel] [varchar] (25) NULL ,'
      #9'[City] [varchar] (45) NULL ,'
      #9'[Adr] [varchar] (145) NULL ,'
      #9'[Bdat] [int] NULL ,'
      #9'[Perc] [float] NULL'
      ') ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Bill] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Bill] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[BillD] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_BillD] PRIMARY KEY  CLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[AcBillList] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_AcBillList] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[AccountKod] WITH NOCHECK ADD'
      '     CONSTRAINT [DF_AccountKod_Barzi] DEFAULT (0) FOR [Barzi],'
      #9'CONSTRAINT [PK_AccountKod] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[AccountPay] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_AccountPay] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[AcountBill] WITH NOCHECK ADD'
      '     CONSTRAINT [DF_AcountBill_Lcheck] DEFAULT (0) FOR [Dchek], '
      #9'CONSTRAINT [PK_AcountBill] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Aghs] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Aghs] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[AnbDat] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_AnbDat] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Kod]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Autobill] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Autobill] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Var]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Banks] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Banks] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[BHav] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_BHav] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[BinvoGood] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_BinvoGood] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Bvoice] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Bvoice] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Cardex] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Cardex] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Cashiers] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Cashiers] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Cent] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Cent] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Cexchange] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Cexchange] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Colors] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Colors] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Costc] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Costc] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[CPerm] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_CPerm] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[CRate] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_CRate] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[CTip] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_CTip] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Depot] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Depot] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[DHav] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DHav] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[DHavG] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DHavG] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[DiRej] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DiRej] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[DiRejG] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DiRejG] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Dout] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Dout] PRIMARY KEY  CLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[DoutG] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_DoutG] PRIMARY KEY  CLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[DoRej] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DoRej] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[DoRejG] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_DoRejG] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[DRes] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_DRes] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[DResG] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_DResG] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Expen] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Expen] PRIMARY KEY  CLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[ExpenD] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_ExpenD] PRIMARY KEY  CLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[FTip] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_FTip] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[GarDesh] WITH NOCHECK ADD'
      '     CONSTRAINT [DF_GarDesh_Dchek] DEFAULT (0) FOR [Dchek],'
      #9'CONSTRAINT [PK_GarDesh] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[GCardex] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_GCardex] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[GChart] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_GChart] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Gform] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Gform] PRIMARY KEY  CLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Goods] WITH NOCHECK ADD'
      '     CONSTRAINT [DF_Goods_flock] DEFAULT (0) FOR [Flock],'
      #9'CONSTRAINT [PK_Goods] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Invogood] WITH NOCHECK ADD'
      #9'CONSTRAINT [DF_Invogood_Delikod] DEFAULT (0) FOR [Delikod],'
      #9'CONSTRAINT [PK_Invogood] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Invoice] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Invoice] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Jari] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Jari] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Idd]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[JariN] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_JariN] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Mali] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Mali] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Move] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Move] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[MoveGood] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_MoveGood] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[NCar] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_NCar] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[NFish] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_NFish] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Pcheq] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Pcheq] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[PInvogood] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_PInvogood] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[PInvoice] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_PInvoice] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[PMon] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_PMon] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Rcheq] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rcheq] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RejBinvogood] WITH NOCHECK ADD '
      #9'CONSTRAINT [DF_RejBinvogood_Bkod] DEFAULT (0) FOR [Bkod],'
      #9'CONSTRAINT [PK_RejBinvogood] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RejBvoice] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_RejBvoice] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RejInvo] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RejInvo] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RejInvogood] WITH NOCHECK ADD '
      #9'CONSTRAINT [DF_RejInvogood_Delikod] DEFAULT (0) FOR [Delikod],'
      #9'CONSTRAINT [PK_RejInvogood] PRIMARY KEY  NONCLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Remit] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Remit] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Remitin] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rmitin] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[RemitOut] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RemitOut] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RKel] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RKel] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Rkeli] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rkeli] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RMon] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RMon] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[RPay] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RPay] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Rpayi] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rpayi] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RRej] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RRej] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Rreji] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rreji] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[RRes] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RRes] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RSaf] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RSaf] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RUKel] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RUKel] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[RUkeli] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_RUkeli] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[Rvos] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Rvos] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Rvosi] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Rvosi] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Tolids] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Tolids] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Users] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_Users] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[UserAc] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_UAccounts] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[UserAct] WITH NOCHECK ADD'
      #9'CONSTRAINT [PK_UserAct] PRIMARY KEY  CLUSTERED'
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY]'
      ''
      'ALTER TABLE [dbo].[VAct] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_VAct] PRIMARY KEY  CLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      'ALTER TABLE [dbo].[Visitors] WITH NOCHECK ADD '
      #9'CONSTRAINT [PK_Visitors] PRIMARY KEY  NONCLUSTERED '
      #9'('
      #9#9'[Id]'
      #9')  ON [PRIMARY] '
      ''
      
        ' CREATE  UNIQUE  INDEX [IX_Bill] ON [dbo].[Bill]([No]) ON [PRIMA' +
        'RY]'
      ''
      ' CREATE  INDEX [IX_BillD] ON [dbo].[BillD]([Dat]) ON [PRIMARY]'
      ''
      
        ' CREATE  INDEX [AccountKod0] ON [dbo].[AccountKod]([Nam]) ON [PR' +
        'IMARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [AcKoIxAccKod] ON [dbo].[AccountKod]([Acc' +
        'kod]) ON [PRIMARY]'
      ''
      
        ' CREATE  INDEX [IX_AcountBill] ON [dbo].[AcountBill]([No]) ON [P' +
        'RIMARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [Autobill0] ON [dbo].[Autobill]([Var]) ON' +
        ' [PRIMARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [Cent0] ON [dbo].[Cent]([Kod]) ON [PRIMAR' +
        'Y]'
      ''
      
        ' CREATE  UNIQUE  INDEX [Costc0] ON [dbo].[Costc]([Nam]) ON [PRIM' +
        'ARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [CPerm0] ON [dbo].[CPerm]([Id]) ON [PRIMA' +
        'RY]'
      ''
      
        ' CREATE  INDEX [DepotIxFind] ON [dbo].[Depot]([Kod], [Color], [A' +
        'nbnam], [Anbkod]) ON [PRIMARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [Goods0] ON [dbo].[Goods]([Nam]) ON [PRIM' +
        'ARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [JariN0] ON [dbo].[JariN]([Nam]) ON [PRIM' +
        'ARY]'
      ''
      
        ' CREATE  UNIQUE  INDEX [Visitors0] ON [dbo].[Visitors]([Code]) O' +
        'N [PRIMARY]'
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ''
      ' '
      ' '
      ' '
      ' ')
    Left = 288
    Top = 112
  end
  object QDb: TQuery
    SQL.Strings = (
      'USE MASTER'
      'CREATE DATABASE  :n'
      'ON'
      '( NAME=:n1,'
      ' FILENAME=:n2,'
      ' SIZE=10,'
      ' MAXSIZE=UNLIMITED ,'
      ' FILEGROWTH=1)'
      'LOG ON'
      '( NAME=:n3,'
      ' FILENAME=:n4,'
      ''
      ' SIZE=10,'
      ' MAXSIZE=UNLIMITED ,'
      ' FILEGROWTH=1)'
      ''
      ' '
      ' '
      ' ')
    Left = 249
    Top = 108
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'n'
        ParamType = ptUnknown
      end
      item
        DataType = ftUnknown
        Name = 'n1'
        ParamType = ptUnknown
      end
      item
        DataType = ftUnknown
        Name = 'n2'
        ParamType = ptUnknown
      end
      item
        DataType = ftUnknown
        Name = 'n3'
        ParamType = ptUnknown
      end
      item
        DataType = ftUnknown
        Name = 'n4'
        ParamType = ptUnknown
      end>
  end
end
